-- Run this file in Supabase SQL Editor.
-- Authentication is handled by Supabase Auth; do not store passwords here.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  role text not null default 'Pembaca aktif',
  avatar text not null default 'BK',
  created_at timestamptz not null default now()
);

create table if not exists public.folders (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  folder_id bigint not null references public.folders(id) on delete restrict,
  title text not null,
  author text not null default 'Impor baru',
  progress integer not null default 0 check (progress between 0 and 100),
  color text not null default 'coral',
  cover_url text,
  file_path text,
  file_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  translation text not null,
  context text not null default '',
  saved_at timestamptz not null default now(),
  unique (user_id, word)
);

create table if not exists public.shares (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  book_id bigint references public.books(id) on delete set null,
  quote text not null,
  created_at timestamptz not null default now()
);

insert into storage.buckets (id, name, public)
values ('books', 'books', false)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.folders enable row level security;
alter table public.books enable row level security;
alter table public.words enable row level security;
alter table public.shares enable row level security;

drop policy if exists "profiles own rows" on public.profiles;
drop policy if exists "folders own rows" on public.folders;
drop policy if exists "books own rows" on public.books;
drop policy if exists "words own rows" on public.words;
drop policy if exists "shares own rows" on public.shares;
drop policy if exists "users upload own books" on storage.objects;
drop policy if exists "users read own books" on storage.objects;
drop policy if exists "users delete own books" on storage.objects;

create policy "profiles own rows" on public.profiles for all using (auth.uid() = id) with check (auth.uid() = id);
create policy "folders own rows" on public.folders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "books own rows" on public.books for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "words own rows" on public.words for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "shares own rows" on public.shares for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users upload own books" on storage.objects for insert to authenticated with check (bucket_id = 'books' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users read own books" on storage.objects for select to authenticated using (bucket_id = 'books' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "users delete own books" on storage.objects for delete to authenticated using (bucket_id = 'books' and (storage.foldername(name))[1] = auth.uid()::text);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, name, avatar)
  values (new.id, coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)), upper(left(coalesce(new.raw_user_meta_data->>'name', 'BK'), 2)));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();
